import type { BlogPost } from './blog-data';

export const actividadesPendientes: BlogPost[] = [
  {
    slug: 'fuegos-submarinos',
    titulo: 'Fuegos artificiales submarinos: química y color en un vaso',
    excerpt: 'Aceite, agua, colorante y sal. Cuatro ingredientes de cocina para crear una explosión de color bajo el agua. Sin fuego, sin peligro.',
    contenido: '',
    categoria: 'ciencia',
    tipo: 'actividad',
    publicado: false,
    autor: 'Tinki',
    fecha: '2026-06-05',
    lecturaMin: 4,
    coverEmoji: '🎆',
    tags: ['química', 'colorante', 'densidad', 'reacción', 'agua'],
    edad: 'maker',
    tiempoMin: 15,
    mancha: 'poco',
    ayuda: 'solo',
    materialesEmoji: [
      { emoji: '🫒', texto: 'Aceite vegetal' },
      { emoji: '💧', texto: 'Agua' },
      { emoji: '🎨', texto: 'Colorante alimentario (varios colores)' },
      { emoji: '🧂', texto: 'Sal fina' },
      { emoji: '🥛', texto: '1 vaso grande transparente' },
    ],
    aprendeCallout: {
      concepto: 'Tu hijo ha visto tres principios científicos en un solo vaso:',
      puntos: ['Densidad: el aceite flota sobre el agua porque es menos denso', 'Solubilidad: el colorante no se mezcla con el aceite, pero sí con el agua', 'Gravedad: la sal arrastra el colorante hacia abajo creando las explosiones de color'],
    },
    sabiasCallout: {
      titular: '¿Sabías que…?',
      dato: 'Los fuegos artificiales reales funcionan con un principio parecido: diferentes sales metálicas producen distintos colores al quemarse. El cobre da verde, el estroncio da rojo, el sodio da amarillo.',
    },
    contenidoEstructurado: {
      intro: '<p>Fuegos artificiales dentro de un vaso de agua. Sin pólvora, sin mecha, sin peligro. Solo aceite, agua, colorante y sal. En 15 minutos tu hijo va a crear una explosión de colores que desafía la gravedad.</p>',
      pasos: [
        { numero: 1, titulo: 'Prepara el escenario', texto: 'Llena un vaso grande con agua hasta 3/4 de su capacidad. Añade con cuidado una capa de aceite vegetal por encima (unos 2 dedos). El aceite flotará sobre el agua. Ya tienes dos capas bien diferenciadas.', imagenDescripcion: 'Vaso con agua y una capa de aceite flotando encima.' },
        { numero: 2, titulo: 'Añade el color', texto: 'Echa unas gotas de colorante alimentario sobre la capa de aceite. Usa varios colores. El colorante no se mezcla con el aceite: se queda en pequeñas bolitas flotando en la capa de aceite porque es soluble en agua pero no en aceite.', imagenDescripcion: 'Gotas de colorante de varios colores flotando sobre la capa de aceite.' },
        { numero: 3, titulo: 'El truco final: la sal', texto: 'Espolvorea una cucharadita de sal fina sobre la superficie. La sal es más densa que el aceite y el agua, así que se hunde arrastrando consigo las gotitas de colorante. Al tocar el agua, el colorante se libera y explota en cascadas de color.', imagenDescripcion: 'Cascadas de colorante cayendo hacia el agua como fuegos artificiales.' },
        { numero: 4, titulo: 'Sigue el espectáculo', texto: 'Las explosiones duran varios minutos. Puedes añadir otra pizca de sal para repetir el efecto. Los colores se mezclan lentamente creando remolinos.', imagenDescripcion: 'Vaso con explosiones de colores en cascada.' },
      ],
      cienciaTitulo: 'Cómo funciona',
      cienciaTexto: '<p>Tres principios en un solo experimento: <strong>densidad</strong> (el aceite flota, la sal se hunde), <strong>polaridad química</strong> (el colorante es polar como el agua, el aceite no polar — no se mezclan), y <strong>gravedad</strong> (la sal arrastra el colorante al caer).</p>',
      soluciones: [
        { problema: 'El colorante se mezcla con el aceite', solucion: 'usa colorante alimentario líquido normal a base de agua, no a base de aceite.' },
        { problema: 'Las explosiones son pequeñas', solucion: 'echa más colorante. Cuantas más gotas, más intenso. Prueba con sal marina en escamas.' },
        { problema: 'La sal no arrastra el colorante', solucion: 'espolvorea la sal justo sobre las gotas de colorante, no en zonas vacías.' },
      ],
      juegoTitulo: 'Laboratorio de colores',
      juegoTexto: '<p>Experimenta: ¿qué pasa con azúcar en lugar de sal? ¿Y con bicarbonato? Prueba con leche en lugar de agua. Haz un timelapse con el móvil.</p>',
      cta: '<p>En Tinkilabs hacemos que la ciencia sea alucinante. Este experimento es un aperitivo de lo que encontrarás en nuestras cajas mensuales.</p><p>[→ Descubre las cajas de este mes]</p>',
    },
  },
  {
    slug: 'pompero-gigante',
    titulo: 'Cómo hacer un pompero gigante con pajitas y cuerda',
    excerpt: 'Dos pajitas, un metro de cuerda y una palangana con jabón. Fabrica un pompero que hace burbujas enormes, del tamaño de tu cabeza.',
    contenido: '',
    categoria: 'proyectos',
    tipo: 'actividad',
    publicado: false,
    autor: 'Tinki',
    fecha: '2026-06-05',
    lecturaMin: 4,
    coverEmoji: '🫧',
    tags: ['burbujas', 'aire libre', 'tensión superficial', 'jabón', 'pompero'],
    edad: 'mini',
    tiempoMin: 15,
    mancha: 'poco',
    ayuda: 'solo',
    materialesEmoji: [
      { emoji: '🧃', texto: '2 pajitas' },
      { emoji: '🪢', texto: '1 metro de cuerda fina o hilo de algodón' },
      { emoji: '🪣', texto: '1 palangana o barreño' },
      { emoji: '🫧', texto: 'Agua + jabón de lavavajillas' },
      { emoji: '✂️', texto: 'Tijeras' },
    ],
    aprendeCallout: {
      concepto: 'Tu hijo ha experimentado con la física de las pompas:',
      puntos: ['Tensión superficial: el agua forma una película elástica gracias al jabón', 'Geometría: la presión del aire se reparte uniformemente creando una esfera', 'Evaporación: las burbujas estallan cuando la capa de agua se evapora'],
    },
    sabiasCallout: {
      dato: 'La burbuja de jabón más grande del mundo medía 32 metros cúbicos y la hizo un artista checo en 2019. Metió a 3 personas dentro.',
    },
    contenidoEstructurado: {
      intro: '<p>Burbujas del tamaño de tu cabeza. Con dos pajitas, un trozo de cuerda y una mezcla de agua con jabón. No necesitas el pompero de plástico del súper. Este hace burbujas 10 veces más grandes y se construye en 5 minutos.</p>',
      pasos: [
        { numero: 1, titulo: 'Fabrica el aro mágico', texto: 'Pasa la cuerda por dentro de las dos pajitas. Ata los extremos formando un círculo. Las pajitas quedan como asas: al separarlas, la cuerda forma un aro grande. Al juntarlas, el aro se cierra.', imagenDescripcion: 'Dos pajitas con cuerda formando un aro.' },
        { numero: 2, titulo: 'Prepara la poción', texto: 'Llena una palangana con 1 litro de agua y añade 100 ml de lavavajillas. Remueve despacio, sin hacer espuma. Para burbujas extra fuertes, añade una cucharada de glicerina (de farmacia).', imagenDescripcion: 'Palangana con mezcla de agua y jabón.' },
        { numero: 3, titulo: 'Sumérgelo y abre', texto: 'Sumerge todo el aro en la mezcla. Sácalo despacio. Se forma una película de jabón en el interior del aro. Separa las pajitas para abrir el aro al máximo y estirar la película.', imagenDescripcion: 'Aro saliendo de la palangana con película de jabón.' },
        { numero: 4, titulo: '¡A volar!', texto: 'Levanta el aro y muévelo despacio hacia atrás. El aire empuja la película y se forma una burbuja gigante que sale volando. Puedes cortar la burbuja con un movimiento seco para soltarla.', imagenDescripcion: 'Burbuja gigante flotando en el aire.' },
      ],
      cienciaTitulo: 'Cómo funciona',
      cienciaTexto: '<p>El agua tiene <strong>tensión superficial</strong>: sus moléculas forman una "piel" elástica. El jabón reduce esa tensión, haciendo la piel más flexible. Al atrapar aire dentro de esa película de agua jabonosa, se forma una burbuja. Es esférica porque la esfera es la forma que menos superficie necesita para encerrar un volumen de aire.</p>',
      soluciones: [
        { problema: 'Las burbujas estallan al formarse', solucion: 'la mezcla de jabón es débil. Añade más lavavajillas o glicerina. Mueve el aro más despacio.' },
        { problema: 'No se forma la película', solucion: 'la cuerda debe estar bien empapada. El algodón absorbe mejor que el nylon.' },
        { problema: 'Las burbujas salen pequeñas', solucion: 'usa una cuerda más larga para un aro más grande. Con 1 metro haces burbujas enormes.' },
      ],
      juegoTitulo: 'Competición de burbujas',
      juegoTexto: '<p>Reta a tu hijo: ¿quién hace la burbuja más grande? ¿Puedes hacer una burbuja dentro de otra? Atrapa una burbuja con las manos mojadas en jabón (las secas las revientan).</p>',
      cta: '<p>En Tinkilabs cada mes construyes algo que funciona de verdad. Este pompero es el plan perfecto para un finde al aire libre. Y si te gusta construir, espera a ver nuestras cajas.</p><p>[→ Descubre Tinkilabs]</p>',
    },
  },
  {
    slug: 'circuito-grafito',
    titulo: 'Cómo dibujar un circuito eléctrico con un lápiz',
    excerpt: 'Un lápiz, un folio y un LED. Dibuja un circuito que enciende una luz de verdad. Sin cables, sin soldador. Grafito, electricidad y magia.',
    contenido: '',
    categoria: 'ingenieria',
    tipo: 'actividad',
    publicado: false,
    autor: 'Tinki',
    fecha: '2026-06-05',
    lecturaMin: 5,
    coverEmoji: '✏️',
    tags: ['circuito', 'electricidad', 'grafito', 'LED', 'electrones'],
    edad: 'pro',
    tiempoMin: 30,
    mancha: 'limpio',
    ayuda: 'adulto',
    materialesEmoji: [
      { emoji: '✏️', texto: '1 lápiz blando (2B o más, mejor 6B)' },
      { emoji: '📄', texto: '1 folio' },
      { emoji: '💡', texto: '1 LED (de 3V o 5V)' },
      { emoji: '🔋', texto: '1 pila de 9V' },
      { emoji: '📎', texto: '2 pinzas de cocodrilo o clips' },
      { emoji: '📏', texto: 'Cinta aislante' },
    ],
    aprendeCallout: {
      concepto: 'Tu hijo ha construido un circuito eléctrico real dibujando con un lápiz:',
      puntos: ['Conductividad: el grafito conduce la electricidad sin necesidad de cables', 'Resistencia: el trazo de grafito limita la corriente como una resistencia', 'Circuito cerrado: la electricidad necesita un camino completo para fluir'],
    },
    sabiasCallout: {
      dato: 'El grafito de los lápices y los diamantes están hechos del mismo material: átomos de carbono. En el diamante forman una estructura durísima. En el grafito forman capas que se deslizan (por eso escribe) y además conducen la electricidad. El mismo elemento, dos personalidades opuestas.',
    },
    contenidoEstructurado: {
      intro: '<p>Un lápiz, un folio, un LED y una pila. Con eso tu hijo va a dibujar un circuito eléctrico que enciende una luz de verdad. Sin cables, sin soldador. Solo una línea de grafito que conduce la electricidad como si fuera un cable de cobre.</p>',
      pasos: [
        { numero: 1, titulo: 'Dibuja el circuito', texto: 'En un folio, dibuja dos líneas gruesas de grafito en paralelo, separadas 2 mm. Repasa varias veces para que queden bien negras y gruesas. Cuanto más grafito, mejor conduce. Deja espacio entre los extremos para el LED.', imagenDescripcion: 'Folio con dos líneas gruesas de grafito dibujadas en paralelo.' },
        { numero: 2, titulo: 'Conecta el LED', texto: 'Coloca el LED haciendo un puente entre las dos líneas. La pata larga (+) a un lado, la corta (-) al otro. Fija las patas con cinta aislante firmemente contra las líneas de grafito.', imagenDescripcion: 'LED colocado sobre las líneas de grafito, patas fijadas con cinta.' },
        { numero: 3, titulo: 'Conecta la pila', texto: 'Conecta los bornes de la pila de 9V a los extremos de las líneas usando pinzas de cocodrilo. Positivo a una línea, negativo a la otra. Asegura buen contacto.', imagenDescripcion: 'Pila de 9V conectada con pinzas a los extremos del circuito.' },
        { numero: 4, titulo: '¡Luz!', texto: 'El LED se enciende. Acabas de construir un circuito eléctrico dibujado a mano. Prueba a hacer líneas más finas: ¿el LED brilla menos? Haz el circuito más largo: ¿se atenúa? La resistencia aumenta con la longitud y disminuye con el grosor.', imagenDescripcion: 'LED encendido sobre el circuito dibujado a lápiz.' },
      ],
      cienciaTitulo: 'Cómo funciona',
      cienciaTexto: '<p>El grafito del lápiz tiene átomos de carbono en capas. Cada átomo tiene un electrón libre que se mueve entre capas. Esos electrones transportan la corriente. La pila empuja los electrones por el circuito: salen del negativo, recorren la línea de grafito, atraviesan el LED (haciéndolo brillar), vuelven por la otra línea al positivo. Circuito cerrado. Electricidad fluyendo. Todo dibujado a lápiz.</p>',
      soluciones: [
        { problema: 'El LED no enciende', solucion: 'la línea de grafito es demasiado fina. Repásala fuerte varias veces. Prueba con un lápiz 6B.' },
        { problema: 'El LED brilla muy poco', solucion: 'acorta el circuito o ensancha las líneas. Más grafito = menos resistencia = más corriente.' },
        { problema: 'El LED se ha fundido', solucion: 'la pila de 9V da demasiada corriente. Usa una pila de botón de 3V o añade una resistencia de 330 ohmios.' },
        { problema: 'Cortocircuito', solucion: 'las dos líneas de grafito se tocan en algún punto. Revisa que estén separadas en todo el recorrido.' },
      ],
      juegoTitulo: 'Laboratorio de circuitos dibujados',
      juegoTexto: '<p>Experimenta: ¿funciona con un rotulador? ¿Y con pintura metálica? Dibuja un circuito con dos LEDs en serie. Fabrica un interruptor: deja un espacio sin grafito y usa un clip como puente para cerrar el circuito.</p>',
      cta: '<p>Este circuito de grafito es el tipo de proyecto que encontrarás en Tinki Pro. Electrónica real, sin pantallas, con componentes que puedes tocar y entender.</p><p>[→ Ver la línea Tinki Pro]</p>',
    },
  },
];
